// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/22/2026, 4:15:21 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/neeldandiwala/Projects/aploy/aploy-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/neeldandiwala/Projects/aploy/aploy-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/neeldandiwala/Projects/aploy/aploy-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/neeldandiwala/Projects/aploy/aploy-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/neeldandiwala/Projects/aploy/aploy-app/plugins/**/*.{js,ts,mjs}","/Users/neeldandiwala/Projects/aploy/aploy-app/composables/**/*.{js,ts,mjs}","/Users/neeldandiwala/Projects/aploy/aploy-app/utils/**/*.{js,ts,mjs}","/Users/neeldandiwala/Projects/aploy/aploy-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/neeldandiwala/Projects/aploy/aploy-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/neeldandiwala/Projects/aploy/aploy-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/neeldandiwala/Projects/aploy/aploy-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;